import type { PdfPayload, PdfSection } from "./itinerarySchema";

function cleanLine(s: string) {
  return (s || "")
    .replace(/\s+/g, " ")
    .replace(/^[•\-\*]\s*/g, "")
    .trim();
}

function isHeading(line: string) {
  const l = line.trim();
  return (
    l.startsWith("#") ||
    l.startsWith("##") ||
    /^[A-Z][A-Za-z0-9\s\/&\-\(\)]+:$/.test(l) ||
    /^(Overview|Highlights|Itinerary|Schedule|Includes|Excludes|Notes|What to bring|Pricing)/i.test(l)
  );
}

function normalizeHeading(line: string) {
  let h = line.trim();
  h = h.replace(/^#+\s*/, "");
  h = h.replace(/:$/, "");
  return h.trim() || "Section";
}

export function parseItineraryToPdfPayload(params: {
  itineraryText: string;
  clientName?: string;
  clientEmail?: string;
  operatorName?: string;
  date?: string;
  fallbackTitle?: string;
}): PdfPayload {
  const raw = (params.itineraryText || "").trim();

  // fallback ikiwa AI imerudisha kitu empty
  const safeRaw = raw.length ? raw : "Itinerary\n\nOverview:\nA custom safari plan will appear here.";

  const lines = safeRaw
    .split("\n")
    .map((l) => l.replace(/\r/g, ""))
    .map((l) => l.trimEnd());

  // title: line ya kwanza yenye maana
  const firstNonEmpty = lines.find((l) => l.trim().length > 0) || params.fallbackTitle || "Safari Itinerary";
  const titleCandidate = cleanLine(firstNonEmpty).replace(/^#+\s*/, "");
  const title = titleCandidate.length >= 4 ? titleCandidate : params.fallbackTitle || "Safari Itinerary";

  // sections parse
  const sections: PdfSection[] = [];
  let current: PdfSection | null = null;

  // anza kuscan kuanzia line ya pili ili title isirudiwe
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    if (isHeading(line)) {
      if (current && current.content.length) sections.push(current);
      current = { heading: normalizeHeading(line), content: [] };
      continue;
    }

    if (!current) current = { heading: "Overview", content: [] };

    // split bullets kama ziko kwenye line moja
    const chunk = line
      .split("•")
      .map(cleanLine)
      .filter(Boolean);

    if (chunk.length) {
      for (const item of chunk) current.content.push(item);
    }
  }

  if (current && current.content.length) sections.push(current);

  // ikiwa bado hakuna sections, tengeneza default
  if (!sections.length) {
    sections.push({
      heading: "Overview",
      content: [cleanLine(safeRaw).slice(0, 2000)],
    });
  }

  return {
    title,
    subtitle: "Generated by Safari Connector AI",
    clientName: params.clientName,
    clientEmail: params.clientEmail,
    operatorName: params.operatorName,
    date: params.date || new Date().toISOString().slice(0, 10),
    sections,
  };
}
